import type { StudioServiceCard } from "@/app/components/sections/StudioServiceCards";

export const digitalExperienceStudioCards: StudioServiceCard[] = [
  {
    yearLabel: "YEAR 2020",
    title: "Website Design & Development",
    description:
      "A premium website experience designed to communicate the brand clearly, improve user trust, and convert visitors into leads through clean visuals, strong content structure, and responsive development.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-1-new.png",
    imageWidth: 820.45,
    imageHeight: 549.69,
    contentMaxWidth: 665,
    backgroundImage: "/imgs/digital-card-bg.png",
    imagePosition: "right",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Landing Page Design",
    description:
      "Focused landing pages built to turn attention into action. We create clear, conversion-led pages for campaigns, launches, products, lead generation, and performance marketing.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-2-new.png",
    imageWidth: 987,
    imageHeight: 782,
    contentMaxWidth: 665,
    backgroundImage: "/imgs/digital-card-2-bg.png",
    gradient: "linear-gradient(135deg, #4F46E5 0%, #2E2A8F 100%)",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "UI/UX, Design System",
    description:
      "Intuitive interfaces and scalable design systems that create consistency across your digital platforms. We design experiences that are easy to use, easy to manage, and built for growth.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-3-new.png",
    imageWidth: 1290,
    imageHeight: 1090,
    contentMaxWidth: 665,
    imageVAlign: "center",
    backgroundImage: "/imgs/digital-card-3-bg.png",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Prototyping / User Testing",
    description:
      "We validate ideas before full development through prototypes, user flows, testing, and feedback. This helps reduce risk, improve usability, and create better digital products from the start.",
    contentMaxWidth: 665,
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-4-new.png",
    imageWidth: 1239,
    overlayImage: "/imgs/digtial-card-4-overlay.png",
    overlayImageWidth: 1114.54,
    overlayImageHeight: 927.1,
    contentVAlign: "center",
    backgroundImage: "/imgs/digital-card-4-bg.jpg",
    imagePosition: "right",
  },
];

export const aiAndThingsStudioCards: StudioServiceCard[] = [
  {
    yearLabel: "YEAR 2020",
    title: "AI Integrations",
    description:
      "AI integrated into websites, apps, workflows, dashboards, and internal systems. We connect AI capabilities where they can improve speed, response quality, decision-making, or operational efficiency.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/ai-card-1-new.png",
    contentMaxWidth: 665,
    backgroundImage: "/imgs/ai-card-bg.png",
    imagePosition: "right",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Chatbots & AI Voice Assistants",
    description:
      "AI assistants built for customer support, lead generation, internal operations, and guided user journeys. We design assistants that are practical, controlled, and aligned with business needs.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/ai-card-2.png",
    imageHeight: 680,
    imageClassName: "lg:pl-[88.63px]",
    contentMaxWidth: 665,
    backgroundImage: "/imgs/ai-card-bg-2.png",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Custom AI Solutions",
    description:
      "Tailored AI tools built around specific business challenges. From data processing to reporting, recommendations, content workflows, and intelligent interfaces, we build AI solutions with a clear use case.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-3-new.png",
    imageWidth: 1290,
    imageHeight: 1090,
    imageVAlign: "center",
    contentMaxWidth: 665,
    gradient: "linear-gradient(135deg, #2FB8A8 0%, #1C6E66 100%)",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Workflow Automation",
    description:
      "Automation designed to reduce repetitive work, improve accuracy, and speed up daily operations. We help businesses connect tools, data, and processes into smarter workflows.",
    industryLabel: "INDUSTRY",
    industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/ai-card-3.png",
    imageWidth: 843,
    imageHeight: 843,
    contentMaxWidth: 665,
    borderColor: "#868686",
    gradient: "#000000",
    imagePosition: "right",
  },
];

export const applicationDevelopmentStudioCards: StudioServiceCard[] = [
  {
    yearLabel: "YEAR 2020",
    title: "Mobile App Development",
    description:
      "Mobile applications designed for real users and real business goals. We build apps that feel smooth, reliable, and easy to use across customer-facing and internal business needs.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/application-card-1.png",
    contentMaxWidth: 665,
    backgroundImage: "/imgs/application-card-bg.jpg",
    imagePosition: "right",
  },
  {
    yearLabel: "YEAR 2020",
    title: "E-commerce Solutions",
    description:
      "Online shopping platforms built for performance, product discovery, secure payments, and scalable growth. We create e-commerce experiences that support both customer experience and business operations.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/application-card-2-new.png",
    imageHeight: 727,
    contentMaxWidth: 665,
    backgroundImage: "/imgs/application-card-bg-2.jpg",
    imagePosition: "right",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Web Applications, CRM, CMS",
    description:
      "Custom web applications, CRM systems, and CMS platforms tailored to your workflows, teams, and business processes. We build systems that simplify operations and improve control.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/application-card-3-new.png",
    imageHeight: 750,
    imageFit: "cover",
    contentMaxWidth: 665,
    gradient: "#000000",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Cloud / Infrastructure",
    description:
      "Secure and reliable cloud infrastructure designed to support performance, uptime, scalability, and future development. We help businesses deploy, manage, and maintain digital platforms with confidence.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/application-card-4-new.png",
    imageHeight: 750,
    imageFit: "cover",
    contentMaxWidth: 665,
    gradient: "#000000",
    imagePosition: "left",
  },
];

export const growthBrandingStudioCards: StudioServiceCard[] = [
  {
    yearLabel: "YEAR 2020",
    title: "SEO, SEM, AIO",
    description:
      "Search visibility built for the way people discover businesses today. We support organic search, paid search, and AI-powered discovery through structured content, technical optimisation, and performance-led strategy.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/growth-card-1-new.png",
    imageHeight: 716,
    contentMaxWidth: 665,
    backgroundImage: "/imgs/growth-card-bg.png",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Branding, Identity & Strategy",
    description:
      "Brands built with clarity, consistency, and purpose. We help define positioning, identity, messaging, visual direction, and strategic foundations that make businesses easier to recognise and remember.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/digital-card-3.png",
    imageHeight: 750,
    imageVAlign: "center",
    contentMaxWidth: 665,
    backgroundImage: "/imgs/growth-card-bg-2-new.png",
    imagePosition: "left",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Performance Campaigns",
    description:
      "Campaigns designed around measurable business growth. We plan, launch, monitor, and optimise digital campaigns focused on qualified traffic, stronger leads, and better conversion.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    image: "/imgs/growth-card-2-new.png",
    imageHeight: 843,
    contentMaxWidth: 665,
    gradient: "#97106594",
    imagePosition: "right",
  },
  {
    yearLabel: "YEAR 2020",
    title: "Analytics & Reporting",
    description:
      "Clear reporting that turns performance data into useful decisions. We help track what matters, understand user behaviour, and improve marketing, content, and platform performance over time.",
    industryLabel: "INDUSTRY",
    // industryValue: "Education",
    ctaText: "Call To Action",
    ctaLink: "/contact-us",
    contentMaxWidth: 665,
    backgroundImage: "/imgs/growth-card-3-bg.png",
    borderColor: "#868686",
    imagePosition: "right",
  },
];
